# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Repo Info
        run: |
          sed -i "s/<!-- REPO_OWNER -->/${{ github.repository_owner }}/g" index.html
          REPO_NAME=$(basename ${{ github.repository }})
          sed -i "s/<!-- REPO_NAME -->/$REPO_NAME/g" index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages