name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inject Repo Info
        run: |
          sed -i "s/<!-- REPO_OWNER -->/${{ github.repository_owner }}/g" index.html
          sed -i "s/<!-- REPO_NAME -->/${{ github.event.repository.name }}/g" index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: .