name: Deploy Space Bookmark Navigator

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Inject repo info into index.html
      run: |
        # 获取当前仓库信息
        USERNAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        
        # 替换index.html中的占位符
        sed -i "s|your-username|$USERNAME|g" index.html
        sed -i "s|your-repo|$REPO|g" index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
