name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Inject repo info into index.html
      run: |
        # 获取仓库信息
        REPO_OWNER="${{ github.repository_owner }}"
        REPO_NAME="${{ github.event.repository.name }}"
        
        # 注入仓库信息到index.html
        sed -i "s|</body>|  <script>window.defaultRepoInfo = { username: '${REPO_OWNER}', repo: '${REPO_NAME}' };</script>\n</body>|" index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        force_orphan: true
