name: Deploy Bookmarks

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的权限设置

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create repo info file (关键备用方案)
        run: |
          # 生成一个独立的JS文件存储仓库信息，避免修改index.html失败
          echo "window.defaultRepo = '${{ github.repository }}';" > repo-config.js
          cat repo-config.js  # 显示生成的内容，用于调试

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          # 简化部署逻辑，避免复杂操作导致失败
