name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 当推送到main分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Inject default repo information
        run: |
          # 获取当前仓库信息 (owner/repo)
          REPO_FULL_NAME="${{ github.repository }}"
          
          # 替换HTML文件中的默认仓库占位符
          # 假设我们在HTML中使用了{{DEFAULT_REPO}}作为占位符
          sed -i "s|const DEFAULT_REPO = \".*\";|const DEFAULT_REPO = \"$REPO_FULL_NAME\";|g" index.html
          
          # 同样更新默认RAW URL
          sed -i "s|const DEFAULT_RAW_URL = \".*\";|const DEFAULT_RAW_URL = \"https://raw.githubusercontent.com/$REPO_FULL_NAME/main/bookmarks.json\";|g" index.html
      
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages  # 部署到gh-pages分支
          folder: .         # 部署当前目录下的文件
          clean: true       # 清理gh-pages分支上的旧文件
          
      - name: Initialize default bookmarks file
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # 检查bookmarks.json是否存在，如果不存在则创建默认文件
          if [ ! -f "bookmarks.json" ]; then
            echo '{"bookmarks": [], "ads": [], "timezones": []}' > bookmarks.json
            git add bookmarks.json
            git commit -m "Initialize default bookmarks.json"
            git push
          fi
