name: Deploy Space Navigation

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Inject repository info
      run: |
        # 获取仓库信息
        REPO_USERNAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        DEPLOY_TIMESTAMP=$(date +%s000)  # 毫秒级时间戳
        
        # 替换index.html中的占位符
        sed -i "s/REPO_USERNAME/$REPO_USERNAME/g" index.html
        sed -i "s/REPO_NAME/$REPO_NAME/g" index.html
        sed -i "s/DEPLOY_TIMESTAMP/$DEPLOY_TIMESTAMP/g" index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
