name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Repo Info
        run: |
          sed -i "s/<!--REPO_OWNER-->/$GITHUB_REPOSITORY_OWNER/g" index.html
          sed -i "s/<!--REPO_NAME-->/$(basename $GITHUB_REPOSITORY)/g" index.html

      - name: Initialize bookmarks.json if not exists
        run: |
          if [ ! -f bookmarks.json ]; then
            echo '{}' > bookmarks.json
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages