name: 部署外太空主题书签导航

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 配置Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: 处理书签数据
        run: |
          # 如果bookmarks.json不存在，创建默认文件
          if [ ! -f "bookmarks.json" ]; then
            echo '{"bookmarks": {"folders": [], "items": []}, "cities": [], "ads": {}, "settings": {}}' > bookmarks.json
          fi
          
          # 确保数据文件有正确的权限
          chmod 644 bookmarks.json
          
      - name: 注入仓库信息到HTML
        run: |
          # 替换index.html中的占位符
          sed -i "s|{{GITHUB_USERNAME}}|${{ github.repository_owner }}|g" index.html
          sed -i "s|{{REPO_NAME}}|${{ github.event.repository.name }}|g" index.html
          sed -i "s|{{DEPLOY_DATE}}|$(date -u +"%Y-%m-%dT%H:%M:%SZ")|g" index.html
          
      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true  # 创建独立的部署分支，不保留历史
          cname: ${{ secrets.CNAME }}  # 可选：自定义域名
          
      - name: 部署完成通知
        if: success()
        run: |
          echo "部署成功！访问地址：https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
    