name: Deploy Space Bookmarks

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        # 获取仓库信息
        REPO_OWNER=${{ github.repository_owner }}
        REPO_NAME=${{ github.event.repository.name }}
        
        # 在index.html中注入默认仓库信息
        sed -i "s|// window.defaultRepoConfig = {};|window.defaultRepoConfig = { username: '$REPO_OWNER', repo: '$REPO_NAME' };|g" index.html
        
        # 如果bookmarks.json不存在，创建它
        if [ ! -f "bookmarks.json" ]; then
            echo '{
                "deployDate": "'$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")'",
                "bookmarks": [],
                "ads": [
                    { "image": "", "url": "" },
                    { "image": "", "url": "" },
                    { "image": "", "url": "" }
                ],
                "cities": [
                    { "name": "北京", "timezone": "+8" },
                    { "name": "伦敦", "timezone": "0" },
                    { "name": "纽约", "timezone": "-5" },
                    { "name": "东京", "timezone": "+9" }
                ]
            }' > bookmarks.json
        fi
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_TOKEN || secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
    