name: Inject Repository Info and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予写入内容的权限
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保获取所有历史记录
    
    - name: Show repository info for debugging
      run: |
        echo "Current repository: ${{ github.repository }}"
        echo "GitHub actor: ${{ github.actor }}"
        echo "Branch: ${{ github.ref }}"
    
    - name: Check if index.html exists
      run: |
        if [ -f "index.html" ]; then
          echo "index.html found"
        else
          echo "Error: index.html not found"
          exit 1
        fi
    
    - name: Inject default repository info
      run: |
        # 获取当前仓库信息 (owner/repo)
        REPO_FULL_NAME="${{ github.repository }}"
        echo "Injecting repo info: $REPO_FULL_NAME"
        
        # 使用更可靠的方法注入仓库信息
        if grep -q "</head>" index.html; then
          sed -i "s|</head>|<script>window.defaultRepo = '${REPO_FULL_NAME}';</script></head>|g" index.html
        else
          # 如果找不到</head>标签，在文件开头添加
          sed -i "1i <script>window.defaultRepo = '${REPO_FULL_NAME}';</script>" index.html
        fi
        
        # 显示注入结果
        echo "Modified index.html content:"
        grep -A 5 "window.defaultRepo" index.html
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./
        force_orphan: false  # 保留历史记录
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
