name: Inject Repository Info

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  inject-repo-info:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check if index.html exists
      run: |
        if [ ! -f "index.html" ]; then
          echo "Error: index.html not found in repository root"
          exit 1
        fi
    
    - name: Show repository info for debugging
      run: |
        echo "Current repository: ${{ github.repository }}"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
    
    - name: Inject default repository info
      run: |
        # 获取当前仓库信息 (owner/repo)
        REPO_FULL_NAME="${{ github.repository }}"
        
        # 创建临时文件存储注入的脚本
        echo "<script>window.defaultRepo = '${REPO_FULL_NAME}';</script>" > repo-script.js
        
        # 更可靠的注入方法：在head标签结束前插入
        sed -i '/<\/head>/e cat repo-script.js' index.html
        
        # 显示注入结果
        echo "Modified index.html content:"
        grep -A 5 "<\/head>" index.html
    
    - name: Verify injection success
      run: |
        if ! grep -q "window.defaultRepo" index.html; then
          echo "Error: Repository info injection failed"
          exit 1
        fi
    
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m "Inject default repo info: ${{ github.repository }}" || echo "No changes to commit"
        git push || echo "Push failed - maybe no changes"
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages  # 明确指定部署到gh-pages分支
